---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: 'Set macOS plist entries for {{ item.key }}'
  osx_defaults:
    domain: '{{ item.key }}'
    key: '{{ setting.key }}'
    type: '{{ setting.type }}'
    value: '{{ setting.value }}'
    state: present
  become: '{{ setting.become|default("yes")|bool }}'
  become_user: '{{ user }}'
  notify:
    - reload controlstrip
  with_items: '{{ item.value }}'
  loop_control:
    loop_var: setting
