---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install X.org keymap config
  import_tasks: xorg-keymap.yml
  when:
    - ansible_facts["system"] == "Linux"
    - roles["desktop"]

- name: Set macOS user defaults
  include_tasks: macos_plist.yml
  with_dict: '{{ macos_defaults }}'
  when:
    - ansible_facts["system"] == "Darwin"
    - roles["desktop"]
