---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Get current network time server
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-getnetworktimeserver'
  register: ntp_server
  changed_when: false
  check_mode: false

- name: Store current network time server for later
  set_fact:
    darwin_ntp_server: '{{ ntp_server.stdout | regex_findall("^Network Time Server: (.+)$") | first }}'

- name: Get is network time being used
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-getusingnetworktime'
  register: using_ntp
  changed_when: false
  check_mode: false

- name: Store if network time is being used for later
  set_fact:
    darwin_using_ntp: '{{ using_ntp.stdout | regex_findall("^Network Time: (.+)$") | first }}'

- name: Set network time server
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-setnetworktimeserver'
      - '{{ ntp_servers[0] }}'
  when: darwin_ntp_server != ntp_servers[0]

- name: Set using network time
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-setusingnetworktime'
      - 'on'
  when: darwin_using_ntp != "On"
