---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install ntpd.conf
  template:
    src: ntpd.conf.j2
    dest: /etc/ntpd.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload ntpd

- name: Start ntpd
  service:
    name: ntpd
    enabled: true
    state: started
