---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Configure BSD networking
  import_tasks: bsd.yml
  when: ansible_facts["system"] == "OpenBSD"

- name: Configure NetworkManager
  import_tasks: networkmanager.yml
  when:
    - ansible_facts["system"] == "Linux"
    - ansible_facts["distribution"] != "Debian"

- name: Configure dhcpcd.conf for Debian servers
  import_tasks: dhcpcd.yml
  when: ansible_facts["distribution"] == "Debian"
