---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: 'Configure NetworkManager daemon'
  template:
    src: 'NetworkManager.conf.j2'
    dest: '/etc/NetworkManager/NetworkManager.conf'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload NetworkManager
