---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install development packages for all platforms
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ packages.all }}'
  when: ansible_facts["system"] != "Darwin"
  check_mode: false

- name: Install development packages for all platforms via Homebrew
  homebrew:
    name: '{{ item }}'
    state: present
  loop: '{{ packages.all }}'
  become: true
  become_user: '{{ user }}'
  check_mode: false
  when: ansible_facts["system"] == "Darwin"

- name: Install development PIP packages
  pip:
    executable: '{{ lookup("first_found", locations) }}'
    name: '{{ item }}'
  become: true
  become_user: '{{ user }}'
  vars:
    locations:
      - /usr/local/bin/pip3
      - /usr/local/bin/pip3.9
      - /usr/local/bin/pip3.8
      - /usr/bin/pip3
      - /usr/bin/pip3.9
      - /usr/bin/pip3.8
  loop: '{{ packages["pip"] }}'

- name: Install development NPM packages
  community.general.npm:
    name: '{{ item }}'
    global: true
  loop: '{{ packages["npm"] }}'

- name: Install development Cargo packages
  community.general.cargo:
    name: '{{ item }}'
  become: true
  become_user: '{{ user }}'
  loop: '{{ packages["cargo"] }}'

- name: 'Platform configuration for {{ ansible_facts["system"] }} for development'
  include_tasks: '{{ ansible_facts["system"]|lower }}.yml'
