---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Queue ddclient package install
  set_fact:
    packages: '{{ packages | combine({"install": packages["install"] + ["ddclient"] }) }}'
  when: ansible_facts["system"] == "Linux"

- name: Queue ddclient service start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["ddclient"] }) }}'
