---
# vim: filetype=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Configure Samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload smb
