---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: gw is a gateway system
  set_fact:
    roles: '{{ roles | combine({"gw": true, "ssh": true, "dhcpd": true}) }}'

- name: Load gw vars
  include_vars: gw.yml

- name: Set dhcpd config
  set_fact:
    dhcpd_config: '{{ dhcpd_config | combine(gw_dhcpd_config) }}'

- name: Set rad config
  set_fact:
    rad_config: '{{ rad_config | combine(gw_rad_config) }}'

- name: Set dhcpcd config
  set_fact:
    dhcpcd_config: '{{ dhcpcd_config | combine(gw_dhcpcd_config) }}'

- name: Set PF WAN interface
  set_fact:
    pf_variables: '{{ pf_variables | combine({"if_wan": "em0"}) }}'

- name: Set PF LAN interface
  set_fact:
    pf_variables: '{{ pf_variables | combine({"if_lan": "em1"}) }}'

- name: Set additional PF variables
  set_fact:
    pf_variables: '{{ pf_variables | combine(gw_pf_variables) }}'

- name: Set PF tables
  set_fact:
    pf_tables: '{{ pf_tables | combine(gw_pf_tables) }}'

- name: Set PF rules
  set_fact:
    pf_rules: '{{ pf_rules + gw_pf_rules }}'

- name: Set OpenBSD gateway sysctls
  set_fact:
    sysctls: '{{ sysctls + gw_sysctls }}'

- name: Set dynamic DNS hosts
  set_fact:
    dyndns_hosts: '{{ dyndns_hosts + gw_hosts }}'

- name: Set HomeAssistant variables
  set_fact:
    homeassistant_vars: '{{ homeassistant_vars | combine(gw_homeassistant_vars) }}'

- name: Queue services to start
  set_fact:
    services: '{{ services | combine({"start": ["slaacd"]}) }}'
