---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Include pihole config
  include_tasks: pihole.yml

- name: Do not require SSHFS mounts
  set_fact:
    roles: '{{ roles | combine({"sshfs_client": false}) }}'

- name: Load hermes vars
  include_vars: hermes.yml

- name: Set IP configuration
  set_fact:
    linux_interfaces: '{{ linux_interfaces | combine(hermes_network_config) }}'

- name: Set backup directories
  set_fact:
    backup_dirs: '{{ backup_dirs + hermes_backup_dirs }}'

- name: No external mounts needed
  set_fact:
    mounts: []

- name: Use external DNS servers
  set_fact:
    dns_servers:
      - 9.9.9.9
      - 8.8.8.8
