---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: nuc is a Docker server system
  set_fact:
    roles: '{{ roles | combine({"docker": true}) }}'

- name: Load nuc vars
  include_vars: nuc.yml

- name: Set Docker services
  set_fact:
    docker_services: '{{ docker_services + nuc_docker_services }}'

- name: Set backup directories
  set_fact:
    backup_dirs: '{{ backup_dirs + nuc_backup_dirs }}'
