---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: nuc is a Docker server system
  set_fact:
    roles: '{{ roles | combine({"docker": true, "sshfs_client": true}) }}'

- name: Load nuc vars
  include_vars: nuc.yml

- name: Set Docker services
  set_fact:
    docker_services: '{{ docker_services + nuc_docker_services }}'

- name: Queue SSHFS mount points
  set_fact:
    mounts: '{{ mounts + nuc_storage_mounts }}'
