---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: pihole is a Docker server system
  set_fact:
    roles: '{{ roles | combine({"docker": true, "sshfs_client": true}) }}'

- name: Load pihole vars
  include_vars: pihole.yml

- name: Set Docker services
  set_fact:
    docker_services: '{{ docker_services + pihole_docker_services }}'

- name: Queue SSHFS mount points
  set_fact:
    mounts: '{{ mounts + pihole_storage_mounts }}'

- name: Set secondary pihole
  set_fact:
    pihole_primary: false
