---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Include pihole config
  include_tasks: pihole.yml

- name: Set primary pihole
  set_fact:
    pihole_primary: true

# This is needed only on the primary
- name: Queue pihole whitelist timer for start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["pihole-whitelist.timer"]}) }}'

- name: Load pihole1 vars
  include_vars: pihole1.yml

- name: Set IP configuration
  set_fact:
    linux_interfaces: '{{ linux_interfaces | combine(pihole1_network_config) }}'
