---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: pihole is a Docker server system
  set_fact:
    roles: '{{ roles | combine({"docker": true, "dns": true}) }}'

- name: Load pihole vars
  include_vars: pihole.yml

- name: Set Docker services
  set_fact:
    docker_services: '{{ docker_services + pihole_docker_services }}'

- name: Set secondary pihole
  set_fact:
    pihole_primary: false

- name: Set backup directories
  set_fact:
    backup_dirs: '{{ backup_dirs + ["/usr/local/etc/pihole"] }}'
