---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

bsd_interfaces:
  em0:
    - 'dhcp'
    - 'inet6 autoconf'
  em1:
    - 'inet 10.0.0.1 255.255.255.0 10.0.0.255'
    - 'inet6 fd01:2345:6789:abcd::1 64'
    - 'up'

sample_sysctls:
  - name: 'net.inet.ip.forwarding'
    value: '1'
  - name: 'net.inet6.ip6.forwarding'
    value: '1'

ipv4_address: '10.0.0.4'
ipv6_address: 'fd01:2345:6789:abcd::4'

sample_pf_rules:
  - 'pass in on $if_lan proto tcp from any to ($if_lan) port { 80 443 } modulate state'
