---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install desktop packages for macOS
  homebrew:
    name: '{{ item }}'
    state: present
  become: true
  become_user: '{{ user }}'
  loop: '{{ packages.macos }}'
  when: ansible_facts["system"] == "Darwin"
