---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install desktop packages for macOS
  homebrew:
    name: '{{ item }}'
    state: present
  become: true
  become_user: '{{ user }}'
  loop: '{{ packages.macos }}'
  check_mode: false

- name: Install macOS pkg installers
  include_tasks: macos_pkg.yml
  loop: '{{ macos_pkg_urls }}'
