---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install desktop packages for Linux
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ packages.linux }}'
  check_mode: false

- name: 'Distro-specific packages for {{ ansible_facts["distribution"] }}'
  include_tasks: '{{ ansible_facts["distribution"]|lower }}.yml'
