---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install desktop packages for all platforms
  package:
    name: '{{ packages.all }}'
    state: present
  when: ansible_facts["system"] != "Darwin"
  check_mode: false

- name: Install desktop packages for all platforms via Homebrew
  homebrew:
    name: '{{ packages.all }}'
    state: present
  become: true
  become_user: '{{ user }}'
  when: ansible_facts["system"] == "Darwin"

- name: 'Platform configuration for {{ ansible_facts["system"] }} as a desktop'
  include_tasks: '{{ ansible_facts["system"]|lower }}.yml'
