---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: save iptables
  command:
    argv:
      - /usr/sbin/iptables-save
      - '-f'
      - '{{ ansible_local.iptables.rules_v4 }}'
  changed_when: false

- name: save ip6tables
  command:
    argv:
      - /usr/sbin/ip6tables-save
      - '-f'
      - '{{ ansible_local.iptables.rules_v6 }}'
  changed_when: false

- name: reload pf
  command:
    argv:
      - /sbin/pfctl
      - '-Fr'
      - '-f'
      - /etc/pf.conf
  changed_when: false
