---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install duplicity packages
  package:
    name:
      - duplicity
      - python3-requests
      - python3-requests-oauthlib

- name: Install systemd units
  template:
    src: 'duplicity-backup.{{ item }}.j2'
    dest: '/usr/local/lib/systemd/system/duplicity-backup.{{ item }}'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload systemd
  loop:
    - service
    - timer

- name: Enable duplicity backup timer
  service:
    name: duplicity-backup.timer
    state: started
    enabled: true