---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Configure dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload dhcpd

- name: Enable dhcpd service
  service:
    name: dhcpd
    enabled: true
    state: started
