---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install Fedora/CentOS repo key
  rpm_key:
    key: '{{ key }}'
    state: present
  when: ansible_facts["distribution"] == "Fedora"
  check_mode: false

- name: Install Debian repo key
  get_url:
    url: '{{ url }}'
    dest: '/etc/apt/trusted.gpg.d/{{ file }}'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  when: ansible_facts["distribution"] == "Debian"
  check_mode: false