---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

# Distributing IPv6 via rad needs dhcpcd to get IPv6 from upstream
- name: Install dhcpcd
  package:
    name: dhcpcd
    state: installed

- name: Configure dhcpcd.conf
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload dhcpcd

- name: Configure rad.conf
  template:
    src: rad.conf.j2
    dest: /etc/rad.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload rad

- name: Start rad and dhcpcd
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - dhcpcd
    - rad
