---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Configure rad.conf
  template:
    src: rad.conf.j2
    dest: /etc/rad.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload rad

- name: Start rad
  service:
    name: rad
    enabled: yes
    state: started
