---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

all:
  children:
    blinkenboxen:
      hosts:
        localhost:
      vars:
        user: 'jgoguen'
        timezone: 'America/Los_Angeles'
        dns_servers:
          - 10.10.0.24
          - 10.10.0.23
        ntp_servers:
          - time1.facebook.com
          - time2.facebook.com
          - time3.facebook.com
          - time4.facebook.com
          - time5.facebook.com
        # Interface definitions.
        # For OpenBSD, maps interface names to lines in the hostname.if(5) file:
        # rl0:
        #    - inet autoconf
        #    - inet6 autoconf
        #    - up
        # For Linux, maps interface names to network config:
        #  eth0:
        #    ip: '192.168.0.100/24'
        #    ip6: 'fe80::beef:100/64'
        #    gateway: 192.168.0.1
        interfaces: {}
        # Gateway definitions in /etc/mygate
        bsd_gateway: []
        pf:
          anchors: {}
          # The interface name on the LAN side
          lan_interface: ''
          # Set true to allow routing to martians
          martians: false
          nat: false
          # Map table name to a map of table data
          # tables:
          #   dns:
          #     const: false
          #     persist: true
          #     file: /etc/pf.tables.d/pf.dns.conf
          #     entries: []
          #   ntp:
          #     const: true
          #     persist: false
          #     file: ''
          #     entries:
          #       - 129.134.28.123
          #       - 129.134.29.123
          tables: {}
          # Map variable name to value
          variables: {}
        sudo_config:
          defaults_flags:
            - '!visiblepw'
            - insults
            - always_set_home
            - match_group_by_gid
            - env_reset
            - always_query_group_plugin
          defaults:
            env_keep:
              - '__CF_USER_TEXT_ENCODING'
              - BLOCKSIZE
              - CHARSET
              - COLORFGBG
              - COLORS
              - COLORTERM
              - DISPLAY
              - EDITOR
              - HOSTNAME
              - HISTSIZE
              - LANG
              - LANGUAGE
              - LC_ADDRESS
              - LC_ALL
              - LC_COLLATE
              - LC_CTYPE
              - LC_IDENTIFICATION
              - LC_MEASUREMENT
              - LC_MESSAGES
              - LC_MONETARY
              - LC_NAME
              - LC_NUMERIC
              - LC_PAPER
              - LC_TELEPHONE
              - LC_TIME
              - LINES_COLUMNS
              - LS_COLORS
              - LSCOLORS
              - MAIL
              - QTDIR
              - KDEDIR
              - SSH_AUTH_SOCK
              - TZ
              - USERNAME
              - VISUAL
              - XAUTHORITY
              - XAUTHORIZATION
            editor: '/usr/bin/nvim:/usr/local/bin/nvim:/usr/bin/vim:/usr/bin/vi:/bin/vi'
            secure_path: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
          users:
            - username: root
              from: ALL
              as_user: ALL
              commands:
                passwd:
                  - ALL
            - username: '%{{ ansible_local.root_owner.sudo }}'
              from: ALL
              as_user: ALL
              commands:
                passwd:
                  - ALL
        doas_rules:
          - 'permit nopass setenv { FTPMODE PKG_CACHE PKG_PATH SM_PATH SSH_AUTH_SOCK DESTDIR DISTDIR FETCH_CMD FLAVOR GROUP MAKE MAKECONF MULTI_PACKAGES NOMAN OKAY_FILES OWNER PKG_DBDIR PKG_DESTDIR PKG_TMPDIR PORTSDIR RELEASEDIR SHARED_ONLY SUBPACKAGE WRKOBJDIR SUDO_PORT_V1 } :wsrc'
          - 'permit persist :wheel'
        iptables_rules:
          - action: insert
            rule_num: '1'
            chain: INPUT
            ip_version: ipv4
            ctstate: INVALID
            jump: DROP
          - action: insert
            rule_num: '1'
            chain: INPUT
            ip_version: ipv6
            ctstate: INVALID
            jump: DROP
          - action: insert
            rule_num: '2'
            chain: INPUT
            ip_version: ipv4
            in_interface: lo
            jump: ACCEPT
          - action: insert
            rule_num: '2'
            chain: INPUT
            ip_version: ipv6
            in_interface: lo
            jump: ACCEPT
          - action: insert
            rule_num: '3'
            chain: INPUT
            ip_version: ipv4
            protocol: icmp
            jump: ACCEPT
          - action: insert
            rule_num: '3'
            chain: INPUT
            ip_version: ipv6
            protocol: icmp
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv4
            ctstate:
              - RELATED
              - ESTABLISHED
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv6
            ctstate:
              - RELATED
              - ESTABLISHED
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv4
            protocol: udp
            destination: 224.0.0.251
            destination_port: '5353'
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv6
            protocol: udp
            destination: 'ff02::fb'
            destination_port: '5353'
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv4
            protocol: udp
            destination: 239.255.255.250
            destination_port: '1900'
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv6
            protocol: udp
            destination: 'ff02::c'
            destination_port: '1900'
            jump: ACCEPT
          - action: append
            chain: INPUT
            ip_version: ipv4
            protocol: udp
            source_port: '67'
            destination_port: '68'
            jump: ACCEPT
        networkmanager_config:
          main:
            plugins: keyfile
            dhcp: dhclient
          connection:
            'ipv6.ip6-privacy': 2
            'wifi.cloned-mac-address': stable
          device:
            'wifi.scan-rand-mac-address': true
        rad_config:
          dns: []
          interfaces: []