---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent

- name: Install systemd units
  template:
    src: 'duplicity-backup.{{ item }}.j2'
    dest: '/usr/local/lib/systemd/system/duplicity-backup.{{ item }}'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload systemd
  loop:
    - service
    - timer
