---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

packages:
  all:
    - youtube-dl
  linux:
    - bluez
    - bluez-tools
    - cups
    - cups-filters
    - cups-pdf
    - cups-pk-helper
    - firefox
    - fontconfig
    - foomatic-db
    - foomatic-db-ppds
  centos: []
  debian: []
  fedora:
    - desktop-file-utils
    - fedora-workstation-repositories
    - gstreamer1
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-extras
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-ugly-free
    - gvfs-afc
    - gvfs-fuse
    - gvfs-goa
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-smb
    - ImageMagick
    - inotify-tools
    - libnotify
    - PackageKit-gstreamer-plugin
    - wl-clipboard
    - xclip
    - xdg-user-dirs-gtk
  openbsd: []
  macos: []
