---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: reload pihole
  community.docker.docker_compose:
    project_src: /opt/docker-compose/pihole
    restarted: true

- name: rebuild pihole
  command: docker-compose -f /opt/docker-compose/pihole/docker-compose.yaml build --pull