---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Configure rad.conf
  template:
    src: rad.conf.j2
    dest: /etc/rad.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload rad

- name: Enable rad service
  service:
    name: rad
    enabled: true
    state: started
