---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: reload systemd
  systemd:
    daemon_reload: true
  changed_when: false

- name: reload docker
  service:
    name: docker
    state: restarted
  changed_when: false

- name: reload watchtower
  community.docker.docker_compose:
    project_src: /opt/docker-compose/watchtower
    restarted: true

# This is a really big hammer, but it's the only way to make sure the remote
# Debian repos are in the cache before we look for packages
- name: flush handlers
  meta: flush_handlers
  check_mode: false