---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent

- name: Install mosquitto.conf
  template:
    src: mosquitto.conf.j2
    dest: /etc/mosquitto.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload mosquitto

- name: Install mosquitto.passwd
  copy:
    src: mosquitto.passwd
    dest: /etc/mosquitto.passwd
    owner: mosquitto
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0600
  notify:
    - reload mosquitto

# Enable and start are split here since flag setting only happens when
# enabling a service
- name: Enable mosquitto
  service:
    name: mosquitto
    enabled: true
    arguments: '-c /etc/mosquitto.conf'

- name: Start mosquitto
  service:
    name: mosquitto
    state: started
