---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Queue development NPM packages for install
  set_fact:
    packages: '{{ packages | combine({"npm": packages["npm"] + npm_packages["devel"]}) }}'
  when: roles["devel"]

- name: Queue development pip packages for install
  set_fact:
    packages: '{{ packages | combine({"pip": packages["pip"] + pip_packages["devel"]}) }}'
  when: roles["devel"]

- name: Queue development cargo packages for install
  set_fact:
    packages: '{{ packages | combine({"cargo": packages["cargo"] + cargo_packages["devel"]}) }}'
  when: roles["devel"]

- name: Queue desktop Flatpak packages for install
  set_fact:
    packages: '{{ packages | combine({"flatpak": packages["flatpak"] + flatpak_packages}) }}'
  when:
    - roles["desktop"]
    - ansible_facts["system"] == "Linux"
