---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent

- name: Create Postgres ansible dir
  file:
    path: /var/postgres/.ansible
    owner: _postgresql
    group: _postgresql
    mode: 0700
    state: directory

- name: postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /usr/local/share/postgres/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0600
  notify:
    - reload postgres

- name: Set up local DB user auth
  community.postgresql.postgresql_pg_hba:
    dest: /usr/local/share/postgres/pg_hba.conf
    contype: local
    databases: samerole
    users: all
    method: peer
    create: yes
  notify:
    - reload postgres

- name: Set up localhost user auth
  community.postgresql.postgresql_pg_hba:
    dest: /usr/local/share/postgres/pg_hba.conf
    contype: host
    databases: samerole
    source: '{{ item }}'
    users: all
    method: scram-sha-256
  with_items:
    - '127.0.0.1/32'
    - '::1/128'
  notify:
    - reload postgres

- name: Enable PostgreSQL
  service:
    name: postgresql
    enabled: yes
    state: started
