---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Queue removal of legacy timesync/NTP packages
  set_fact:
    packages: '{{ packages | combine({"remove": packages["remove"] + ["chrony"]}) }}'

- name: Queue NTP services for start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["systemd-timesyncd"]}) }}'
