---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install SSH global known hosts
  copy:
    src: ssh_known_hosts
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
