---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: reload unifi-controller
  community.docker.docker_compose:
    project_src: /opt/docker-compose/unifi-controller
    restarted: true