---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Configure doas
  template:
    src: doas.j2
    dest: /etc/doas.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0600
    validate: /usr/bin/doas -C %s
