---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Configure sudo
  import_tasks: sudo.yml
  when: ansible_facts["system"] != "OpenBSD"

- name: Configure doas
  import_tasks: doas.yml
  when: ansible_facts["system"] == "OpenBSD"
