---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Queue UniFi Controller iptables rules
  set_fact:
    iptables_rules: '{{ iptables_rules + unifi_controller_iptables_rules }}'
  when: install_compose
