---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: reload ntpd
  service:
    name: ntpd
    state: restarted
  changed_when: false

- name: reload timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
  changed_when: false
