---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Set sysctl values
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
    sysctl_set: yes
  loop: '{{ sysctls | dict2items }}'
