---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent

- name: Set network time server
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-setnetworktimeserver'
      - '{{ ntp_servers[0] }}'
  when: darwin_ntp_server != ntp_servers[0]

- name: Set using network time
  command:
    argv:
      - /usr/sbin/systemsetup
      - '-setusingnetworktime'
      - 'on'
  when: darwin_using_ntp != "On"
