---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install timesyncd.conf
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload timesyncd
