---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Queue pihole iptables rules
  set_fact:
    iptables_rules: '{{ iptables_rules + pihole_iptables_rules }}'
  when: install_compose

- name: Queue pihole proxy iptables rules
  set_fact:
    iptables_rules: '{{ iptables_rules + pihole_proxy_iptables_rules }}'
  when: install_proxy

- name: Queue systemd-resolved for stop
  set_fact:
    services: '{{ services | combine({"stop": services["stop"] + ["systemd-resolved"]}) }}'
  when: install_compose

- name: Dequeue systemd-resolved from starting
  set_fact:
    services: '{{ services | combine({"start": services["start"] | reject("equalto", "systemd-resolved") | list}) }}'
  when: install_compose

- name: Queue pihole-cloudsync for start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["pihole-cloudsync.timer"]}) }}'
  when: install_compose
