---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install acme-client.conf
  template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    owner: 'root'
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644

- name: Create ACME directory
  file:
    path: /etc/acme
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0700
    state: directory
  check_mode: false

- name: Install ACME account key
  copy:
    src: acme.key
    dest: /etc/acme/letsencrypt-privkey.pem
    owner: 'root'
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0400

- name: Renew certificates cron tasks
  cron:
    name: 'Renew certs for {{ item }}'
    minute: '{{ 59 | random(seed=item) }}'
    hour: '{{ 9 | random(seed=item) }}'
    job: '/usr/sbin/acme-client {{ item }}'
  loop: '{{ certbot_hosts }}'
