---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

dependencies:
  - role: exec/packages
  - role: exec/firewall
  - role: exec/certbot
  - role: exec/gw
  - role: exec/dns
  - role: exec/networking
  - role: exec/common
  - role: exec/dhcpd
  - role: exec/dyndns
  - role: exec/sysctl
  - role: exec/sudo
  - role: exec/sshd
  - role: exec/desktop
  - role: exec/firefox
  - role: exec/unbound
  - role: exec/mqtt
  - role: exec/unifi
  - role: exec/dyndns
  - role: exec/ntp
  - role: exec/services
  - role: exec/db
