---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Configure BSD networking
  import_tasks: bsd.yml
  when: ansible_facts["system"] == "OpenBSD"

- name: Configure NetworkManager for desktops
  import_tasks: networkmanager.yml
  when:
    - ansible_facts["system"] == "Linux"
    - roles["desktop"]
