---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Queue VS Code yum repo inclusion
  set_fact:
    repos: '{{ repos + [vscode_yum_repo] }}'
  when: ansible_facts["distribution"] == "Fedora"

- name: Queue VS Code repo key
  set_fact:
    repo_keys: '{{ repo_keys + [vscode_repo_key] }}'

# For now, this only applies to Fedora
- name: Queue VS Code package install
  set_fact:
    packages: '{{ packages | combine({"install": packages["install"] + ["code-insiders"]}) }}'
  when: ansible_facts["distribution"] == "Fedora"
