---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: OpenBSD ddclient config path
  set_fact:
    ddclient_conf: /etc/ddclient/ddclient.conf
  when: ansible_facts["system"] == "OpenBSD"

- name: Linux ddclient config path
  set_fact:
    ddclient_conf: /etc/ddclient.conf
  when: ansible_facts["system"] == "Linux"

- name: Install ddclient config
  template:
    src: ddclient.conf
    dest: '{{ ddclient_conf }}'
    owner: root
    group: '_ddclient'
    mode: 0640
  notify:
    - reload ddclient
