---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Install ddclient config
  template:
    src: ddclient.conf
    dest: /etc/ddclient/ddclient.conf
    owner: root
    group: '_ddclient'
    mode: 0640
  notify:
    - reload ddclient
