---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: reload systemd
  systemd:
    daemon_reload: true
  changed_when: false

- name: reload docker
  service:
    name: docker
    state: restarted
  changed_when: false

- name: reload caddy
  service:
    name: caddy
    state: restarted
  changed_when: false
