---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: reload docker
  service:
    name: docker
    state: restarted
  changed_when: false

- name: reload caddy
  service:
    name: caddy
    state: restarted
  changed_when: false
