---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Update iptables
  iptables: '{{ item }}'
  notify:
    - save iptables
    - save ip6tables
  loop: '{{ iptables_rules }}'

- name: Set iptables policies
  iptables:
    chain: '{{ item.key }}'
    policy: '{{ item.value }}'
    ip_version: ipv4
  notify:
    - save iptables
  loop: '{{ iptables_policies | dict2items }}'

- name: Set ip6tables policies
  iptables:
    chain: '{{ item.key }}'
    policy: '{{ item.value }}'
    ip_version: ipv6
  notify:
    - save ip6tables
  loop: '{{ iptables_policies | dict2items }}'
