---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Configure iptables
  import_tasks: iptables.yml
  when: ansible_facts["system"] == "Linux"

- name: Configure PF
  import_tasks: pf.yml
  when: ansible_facts["system"] == "OpenBSD"
