---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: 'Install fonts to {{ ansible_local.fonts.dir }}'
  copy:
    src: fonts/
    dest: '{{ ansible_local.fonts.dir }}'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
    directory_mode: 0755
