---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Install udev rules
  template:
    src: '{{ item }}.udev'
    dest: '/etc/udev/rules.d/00-{{ item }}.conf'
    owner: '{{ ansible_local.root_owner.user }}'
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload udev
  with_items:
    - tpm
    - u2f
