---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: save iptables
  command:
    argv:
      - /usr/sbin/iptables-save
      - '-f'
      - '{{ ansible_local.iptables.rules_v4 }}'

- name: save ip6tables
  command:
    argv:
      - /usr/sbin/ip6tables-save
      - '-f'
      - '{{ ansible_local.iptables.rules_v6 }}'

- name: reload pf
  command:
    argv:
      - /sbin/pfctl
      - '-Fr'
      - '-f'
      - /etc/pf.conf
