---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install packages for Linux
  package:
    name: '{{ packages.linux }}'
    state: present
  check_mode: false

- name: 'Distro-specific configuration for {{ ansible_facts["distribution"] }}'
  include_tasks: '{{ ansible_facts["distribution"]|lower }}.yml'
