---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Install packages for Linux
  package:
    name: '{{ packages.linux }}'
    state: present
  check_mode: false

- name: Set sysctl dictionary
  set_fact:
    sysctls:
      'fs.inotify.max_user_watches': 5000000
      'fs.protected_hardlinks': 1
      'fs.protected_symlinks': 1
      'fs.suid_dumpable': 0
      'kernel.dmesg_restrict': 1
      'kernel.kptr_restrict': 1
      'kernel.sysrq': 1
      'net.ipv4.conf.all.accept_redirects': 0
      'net.ipv4.conf.all.accept_source_route': 0
      'net.ipv4.conf.all.rp_filter': 0
      'net.ipv4.conf.all.secure_redirects': 0
      'net.ipv4.conf.all.send_redirects': 0
      'net.ipv4.conf.default.accept_redirects': 0
      'net.ipv4.conf.default.accept_source_route': 0
      'net.ipv4.conf.default.rp_filter': 0
      'net.ipv4.conf.default.secure_redirects': 0
      'net.ipv4.conf.default.send_redirects': 0
      'net.ipv4.icmp_echo_ignore_broadcasts': 1
      'net.ipv4.icmp_ignore_bogus_error_responses': 1
      'net.ipv4.tcp_mtu_probing': 1
      'net.ipv4.tcp_syncookies': 1
      'net.ipv4.tcp_tw_reuse': 1
      'net.ipv4.tcp_fastopen': 3
      'net.ipv6.conf.all.accept_redirects': 0
      'net.ipv6.conf.all.accept_source_route': 0
      'net.ipv6.conf.all.addr_gen_mode': 3
      'net.ipv6.conf.all.use_tempaddr': 2
      'net.ipv6.conf.default.accept_redirects': 0
      'net.ipv6.conf.default.accept_source_route': 0
      'net.ipv6.conf.default.addr_gen_mode': 3
      'net.ipv6.conf.default.use_tempaddr': 2
      'vm.dirty_bytes': 4194304
      'vm.dirty_background_bytes': 4194304
      'vm.min_free_kbytes': 209715
      'vm.swappiness': 5
      'vm.vfs_cache_pressure': 50

- name: Add sysctls not valid on Debian
  set_fact:
    sysctls: '{{ sysctls | combine({"kernel.hardlockup_panic": 1, "kernel.nmi_watchdog": 0}) }}'
  when: ansible_facts["distribution"] != "Debian"

- name: Set sysctl values for Linux
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
    sysctl_set: yes
  loop: '{{ sysctls | dict2items }}'

- name: Create systemd local unit directory
  file:
    path: /usr/local/lib/systemd/system
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0755
    state: directory

- name: Install udev rules
  template:
    src: '{{ item }}.udev'
    dest: '/etc/udev/rules.d/00-{{ item }}.conf'
    owner: '{{ ansible_local.root_owner.user }}'
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  notify:
    - reload udev
  with_items:
    - tpm
    - u2f

- name: Install modprobe config
  template:
    src: '{{ item }}.conf'
    dest: '/etc/modprobe.d/{{ item }}.conf'
    owner: root
    group: '{{ ansible_local.root_owner.group }}'
    mode: 0644
  with_items:
    - hid_apple
    - pcspkr
    - snd_hda_intel

- name: 'Distro-specific configuration for {{ ansible_facts["distribution"] }}'
  include_tasks: '{{ ansible_facts["distribution"]|lower }}.yml'
