---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: Add DNS PF table
  set_fact:
    pf_tables: '{{ pf_tables | combine(pf_dns_tables) }}'

- name: Add DNS PF rules
  set_fact:
    pf_rules: '{{ pf_rules + pf_dns_rules }}'

- name: Set current interface addresses
  set_fact:
    current_unbound_ifaces: '{{ unbound_config["server"]["interface"] }}'

- name: Add host IP addresses for binding
  set_fact:
    current_unbound_ifaces: '{{ current_unbound_ifaces + [ ipv4_address, ipv6_address ] }}'

- name: Add interface addresses for binding
  set_fact:
    unbound_config: '{{ unbound_config | combine({"server": {"interface": current_unbound_ifaces }}, recursive=True) }}'

- name: Set auth zones configs
  set_fact:
    unbound_config: '{{ unbound_config | combine({"auth-zone": unbound_config["auth-zone"] + default_auth_zones}, recursive=True) }}'

- name: Queue unbound service start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["unbound"]}) }}'
