---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

jellyfin_iptables_rules:
  - action: append
    chain: INPUT
    ip_version: ipv4
    protocol: udp
    destination_port: '7359'
    jump: ACCEPT
  - action: append
    chain: INPUT
    ip_version: ipv6
    protocol: udp
    destination_port: '7359'
    jump: ACCEPT
  - action: append
    chain: INPUT
    ip_version: ipv4
    protocol: tcp
    destination_port: '8096'
    jump: ACCEPT
  - action: append
    chain: INPUT
    ip_version: ipv6
    protocol: tcp
    destination_port: '8096'
    jump: ACCEPT
