---
# vim: set filetype=yaml.ansible expandtab sts=2 sw=2 nospell:

- name: Queue duplicity install
  set_fact:
    packages: '{{ packages | combine({"install": packages["install"] + ["duplicity", "python3-requests", "python3-requests-oauthlib"] }) }}'

- name: Queue duplicity backup start
  set_fact:
    services: '{{ services | combine({"start": services["start"] + ["duplicity-backup.timer"]}) }}'
