---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent

- name: Set certbot host for DB
  set_fact:
    certbot_hosts: '{{ certbot_hosts + ["db.intern.jgoguen.ca"] }}'

- name: Set dynamic DNS host for DB
  set_fact:
    dyndns_hosts: '{{ dyndns_hosts + ["db.intern.jgoguen.ca"] }}'

- name: Queue DB packages for install
  set_fact:
    packages: '{{ packages | combine({"install": packages["install"] + ["postgresql-server", "postgresql-client"] }) }}'

- name: Queue DB PF rules
  set_fact:
    pf_rules: '{{ pf_rules + db_pf_rules }}'
