---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: reload rad
  service:
    name: rad
    state: restarted
  changed_when: false

- name: reload dhcpcd
  service:
    name: dhcpcd
    state: restarted
  changed_when: false
