---
# vim: filetype=ansible:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell

- name: reload systemd
  systemd:
    daemon_reload: true
  changed_when: false

- name: reload udev
  command:
    argv:
      - /usr/bin/udevadm
      - control
      - '--reload'
  changed_when: false
